[server]
headless = true
port = 8501

[theme]
primaryColor = "#b7622c"              # burnt-caramel akcent
backgroundColor = "#20100e"           # coffee-bean tło
secondaryBackgroundColor = "#323232"  # graphite tło paneli
textColor = "#F5F0E8"                 # ciepła biel
font = "sans serif"
