[server]
headless = true
port = 8501

[theme]
primaryColor = "#b7622c"              # burnt-caramel akcent
backgroundColor = "#323232"           # graphite tło
secondaryBackgroundColor = "#20100e"  # coffee-bean tło paneli
textColor = "#F5F0E8"                 # ciepła biel
font = "sans serif"

[theme.sidebar]
backgroundColor = "#20100e"           # coffee-bean
secondaryBackgroundColor = "#323232"  # graphite
primaryColor = "#b7622c"              # burnt-caramel
textColor = "#F5F0E8"                 # ciepła biel
borderColor = "#4a3c39"               # obramowanie widgetów
