[server]
headless = true
port = 8501

[theme]
primaryColor = "#4CAF50"           # Zielony akcent
backgroundColor = "#121212"        # Główne tło
secondaryBackgroundColor = "#1E1E1E"  # Tło paneli
textColor = "#EAEAEA"              # Jasny tekst
font = "sans serif"
